### ISSUE TITLE
Update to latest version of gpii-launcher to address Synk warnings with transitive dependencies

### ISSUE THREAD

**Issue by colinbdclark** [colinbdclark/flocking-midi-router#8]
Synk is currenty reporting several upstream security issues that stem from gpii-launcher's dependency on an old version of Kettle.

@the-t-in-rtf has updated gpii-launcher to the latest version of Kettle, which in turn has updated to patched versions of the ws and qs dependencies. We should upgrade to <code>1.0.0-dev.20170712T140305Z.aa60d4a</code>.

**Comment by colinbdclark** [comment]
@the-t-in-rtf, when I upgrade to the latest development release of gpii-launchers, I get the following errors when running flocking-midi-router:

2:14:00.271:  Registering module flocking-midi-router from path /Users/colin/code/flocking-midi-router
YError: Too many arguments provided. Expected max 1 but received 2.
    at module.exports (/Users/colin/code/flocking-midi-router/node_modules/yargs/lib/argsert.js:31:13)
    at Object.Yargs.self.array (/Users/colin/code/flocking-midi-router/node_modules/yargs/yargs.js:184:5)
    at /Users/colin/code/flocking-midi-router/node_modules/gpii-launcher/src/js/launcher.js:41:23
    at Object.fluid.each (/Users/colin/code/flocking-midi-router/node_modules/infusion/src/framework/core/js/Fluid.js:517:17)
    at gpii.launcher.launchComponent (/Users/colin/code/flocking-midi-router/node_modules/gpii-launcher/src/js/launcher.js:40:11)
    at togo (/Users/colin/code/flocking-midi-router/node_modules/infusion/src/framework/core/js/FluidIoC.js:1794:33)
    at Object.fire (/Users/colin/code/flocking-midi-router/node_modules/infusion/src/framework/core/js/Fluid.js:1494:40)
    at Object.fluid.initComponent (/Users/colin/code/flocking-midi-router/node_modules/infusion/src/framework/core/js/Fluid.js:2671:30)
    at Function.creator [as launcher] (/Users/colin/code/flocking-midi-router/node_modules/infusion/src/framework/core/js/Fluid.js:1925:30)
    at Object.<anonymous> (/Users/colin/code/flocking-midi-router/launcher.js:50:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
node . [options]

Any thoughts on what might be causing this?

**Comment by the-t-in-rtf** [comment]
It seems like a yargs error, but I haven't updated the version of yargs in ages.  What version of gpii-launcher did you have before?  Also, do you have a branch somewhere with this update that I could try out?

**Comment by colinbdclark** [comment]
See above ;)

https://github.com/colinbdclark/flocking-midi-router/commit/bc8df85acc631c952226bdbf492ae690539af7b2

**Comment by the-t-in-rtf** [comment]
Sorry for the extreme delay.  I have tracked this down and filed [GPII-2592](https://issues.gpii.net/browse/GPII-2592).  There is a workaround in the linked issue, which you should only need if the problem is an underlying issue with yargs.  More in a bit.
